---
title: "ptoolkit for R"
author: "Amy Goldlist, Esteban Angel, Veronique Mulholland"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ptoolkit for R}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Key Features

p_toolkit is a package designed to help adjust and visualize p-values when using multiple comparisons.  As computing power has become powerful enough to run hundreds or even thousands of statistical tests, it is important to look at small p-values and try to understand whether the result is small simply by chance, or whether it truly is significant.  There are many tools to help decide when to reject a Null hypothesis, which can control either:

*  The chance of committing a type 1 error (rejecting a null hypothesis given that it is true) on a single test
* The chance of committing at least one type 1 error in *m* tests
* The chance of a null hypothesis being true given that we have rejected it, the False Discovery rate (FDR)

We can use the p-values alone, or an adjustment method such as the Bonferroni  or the Benjamini-Hochberg (BH) methods.  We can also use visualization methods such as QQ-plots or a scatter plot of the p-values, to try and detect patterns.

This package aims to combine these methods in a simple-to-use format, which works by outputting dataframes, which contain results from several adjustment methods.

### Package Functions
 * **p_adjust(data, pv_index, method, alpah =0.05)**:  Input a vector or a dataframe with the p-values indexed, and it will output a dataframe containgn the data plus adjusted p-values via the BH method, or the Bonferroni
 
 * **p_methods(data, pv_index, alpha =0.5)**:  Input a vector or a dataframe with the p-values indexed, and it will output a dataframe containing the original data, plus critical values and whether the result is significant or not under both the BH and Bonferroni method.


* **p_qq(data, pv_index)**: Input a vector or dataframe and column index, and it will output a qqplot of the p-values compared with the uniform distribution.

* **p_plot(data, pv_index, alpha =0.5)**: Input a vector or dataframe and column index,it will output a ggplot with the p-values and both cut-off lines.

## Credits

* README formatting inspiration from  [Markdownify](https://github.com/amitmerchant1990/electron-markdownify/blob/master/README.md#key-features)
* Badges by [Shields IO](https://shields.io/)
* Logo by [Devendra Karkar](https://www.iconfinder.com/dev-patel)




### Package Dependencies

This package requires dplyr and ggplot2

### Similar Packages and Functions

Some packages already exist for the p-value adjustment in both environments, R and Python:

**R:**

* [`stats::p.adjust`](https://www.rdocumentation.org/packages/stats/versions/3.4.3)

The `p.adjust` function comes in the base `stats` library in R. It's a function designed for adjusting an array of p-values using six methods, some for controlling the family-wise error ("holm", "Hochberg", "Hommel", "Bonferroni") and the others for controlling the false discovery rate ("BH", "BY","fdr"). The advantage of this function is its simplicity and that it comes in the `stats` library, which is built in in the default environments in R, so the user doesn't need to install external packages. It doesn't let the user analyze deeper what is going on with the tests; this is a key element of `p_toolkit`.

* [`fdrtool`](https://www.rdocumentation.org/packages/fdrtool/versions/1.2.15)

`fdrtool` is a package designed for analyzing the False Discovery Rate in statistical tests and not limited exclusively to p-value adjustment. Has some functions related to `p_toolkit` like `fdrtool`, which calculates and plots the false discovery rate and `pval.estimate.eta0`, which outputs the proportion of null p-values in a list.


**Python:**

* [`statsmodels.sandbox.stats.multicomp.multipletests`](http://www.statsmodels.org/devel/generated/statsmodels.sandbox.stats.multicomp.multipletests.html#statsmodels.sandbox.stats.multicomp.multipletests)

This function is part of the `statsmodels` library, a complete set of functions for implementing statistical methods in Python. It works similar to R's `p.adjust`, receiving an array of p-values as inputs and returning two arrays: one with the corrected p-values and another one with boolean values corresponding to the new logical values after correction. It has no diagnostics and analysis of the results.

## License

[MIT License](https://github.com/UBC-MDS/p_toolkit_Python/blob/master/LICENSE)

Interested in contributing?
See our [Contributing Guidelines](https://github.com/UBC-MDS/p_toolkit_Python/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/UBC-MDS/p_toolkit_Python/blob/master/Conduct.md).

---

Created by

[Amy Goldlist](https://github.com/amygoldlist) &nbsp;&middot;&nbsp;
[Esteban Angel](https://github.com/estebanangelm) &nbsp;&middot;&nbsp;
[Veronique Mulholland](https://github.com/vmulholl)



